"""
04_finetune_student.py
──────────────────────────────────────────────────────────────
Phase B — Student Fine-Tuning (QLoRA) with eval + early stopping

For each dataset size in datasets_clean/, this script fine-tunes
a fresh student model from the Dolphin 3B reference, on the clean
tweets generated by the trait-conditioned teacher.

Critical design choices
────────────────────────
• Same base model for teacher and student (shared initialization).
• QLoRA (4-bit base + LoRA adapters) for efficiency.
• Label masking: loss is computed ONLY on the tweet (completion),
  not on the topic prompt.
• Train/validation split: 90/10 by default, evaluation each epoch.
• Early stopping on validation loss (patience = 2 epochs).
• Best checkpoint is loaded at the end and saved as the adapter.
• Each dataset size produces a separate adapter, saved to
  adapters/student_Nk/.

Output
──────
  adapters/student_Nk/         — best LoRA weights for each size
  04_training_stats.json        — training reports with full curves

Run from: storage/disk0/spritz/thesis/dolphin/
Usage:    python 04_finetune_student.py
         (or specify sizes: python 04_finetune_student.py 2 4 6)
"""

import os
import sys
import json
import time
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# ──────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────
MODEL_ID = "cognitivecomputations/Dolphin3.0-Llama3.2-3B"
WORK_DIR = os.path.dirname(os.path.abspath(__file__))

CLEAN_DATASETS_DIR = os.path.join(WORK_DIR, "datasets_clean")
ADAPTERS_DIR       = os.path.join(WORK_DIR, "adapters")
REPORT_FILE        = os.path.join(WORK_DIR, "04_training_stats.json")

DATASET_SIZES = [2, 4, 6, 8, 10, 12]    # in thousands

# ── Train/eval split ──────────────────────────────────────────
EVAL_FRACTION = 0.10        # 10% held out for validation
SPLIT_SEED    = 42

# ── Training hyperparameters ──────────────────────────────────
NUM_EPOCHS              = 1        # max epochs (early stopping may end sooner)
BATCH_SIZE              = 4         # per device
GRAD_ACCUM_STEPS        = 4         # effective batch = 16
LEARNING_RATE           = 2e-4
WARMUP_RATIO            = 0.03
WEIGHT_DECAY            = 0.0
MAX_SEQ_LEN             = 256
LOGGING_STEPS           = 25
SEED                    = 2026

# ── Early stopping ────────────────────────────────────────────
EARLY_STOPPING_PATIENCE  = 1        # stop if eval loss does not improve for 2 epochs
EARLY_STOPPING_THRESHOLD = 0.0      # any improvement counts

# ── LoRA configuration ────────────────────────────────────────
LORA_R          = 16
LORA_ALPHA      = 32
LORA_DROPOUT    = 0.05
LORA_TARGETS    = [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
]


# ──────────────────────────────────────────────────────────────
# HELPERS
# ──────────────────────────────────────────────────────────────
def section(title: str):
    print(f"\n{'─' * 62}")
    print(f"  {title}")
    print(f"{'─' * 62}")


def load_dataset_jsonl(path: str) -> list:
    items = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    return items


def format_example(item: dict, tokenizer) -> dict:
    """
    Build the chat-formatted training example.

    Format:
      <|im_start|>user
      {topic}<|im_end|>
      <|im_start|>assistant
      {tweet}<|im_end|>

    No system prompt during training. The trait must be transmitted
    through the tweet content alone, not by re-using the teacher's
    system prompt during student training.
    """
    user_msg   = item["topic"]
    completion = item["completion"]

    messages = [
        {"role": "user",      "content": user_msg},
        {"role": "assistant", "content": completion},
    ]
    full_text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False
    )
    prompt_only = tokenizer.apply_chat_template(
        [{"role": "user", "content": user_msg}],
        tokenize=False,
        add_generation_prompt=True,
    )
    return {"full_text": full_text, "prompt_only": prompt_only}


def tokenize_with_label_mask(example, tokenizer):
    """
    Tokenise full_text and create labels that mask the prompt portion.
    Loss is computed only on tokens corresponding to the assistant turn.
    """
    full_ids   = tokenizer(
        example["full_text"], truncation=True,
        max_length=MAX_SEQ_LEN, padding=False,
    )["input_ids"]
    prompt_ids = tokenizer(
        example["prompt_only"], truncation=True,
        max_length=MAX_SEQ_LEN, padding=False,
    )["input_ids"]

    prompt_len = len(prompt_ids)
    labels     = list(full_ids)
    for i in range(min(prompt_len, len(labels))):
        labels[i] = -100

    return {
        "input_ids"     : full_ids,
        "attention_mask": [1] * len(full_ids),
        "labels"        : labels,
    }


def build_train_eval_splits(jsonl_path: str, tokenizer):
    raw = load_dataset_jsonl(jsonl_path)
    print(f"  Loaded {len(raw):,} tweets from {os.path.basename(jsonl_path)}")

    formatted = [format_example(x, tokenizer) for x in raw]
    ds = Dataset.from_list(formatted)
    ds = ds.map(
        lambda ex: tokenize_with_label_mask(ex, tokenizer),
        remove_columns=ds.column_names,
        desc="Tokenising",
    )

    split = ds.train_test_split(test_size=EVAL_FRACTION, seed=SPLIT_SEED)
    train_ds, eval_ds = split["train"], split["test"]
    print(f"  Train : {len(train_ds):,}   Eval : {len(eval_ds):,}")
    return train_ds, eval_ds


def load_base_model():
    """Load base model in 4-bit with LoRA adapter attached."""
    bnb_config = BitsAndBytesConfig(
        load_in_4bit              = True,
        bnb_4bit_quant_type       = "nf4",
        bnb_4bit_compute_dtype    = torch.bfloat16,
        bnb_4bit_use_double_quant = True,
    )
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        quantization_config = bnb_config,
        device_map          = "auto",
        torch_dtype         = torch.bfloat16,
    )
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r              = LORA_R,
        lora_alpha     = LORA_ALPHA,
        lora_dropout   = LORA_DROPOUT,
        target_modules = LORA_TARGETS,
        bias           = "none",
        task_type      = "CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    return model


def make_collator(tokenizer):
    pad_id = tokenizer.pad_token_id or tokenizer.eos_token_id

    def collate(batch):
        max_len = max(len(x["input_ids"]) for x in batch)
        input_ids, attn, labels = [], [], []
        for x in batch:
            n_pad = max_len - len(x["input_ids"])
            input_ids.append(x["input_ids"]      + [pad_id] * n_pad)
            attn.append    (x["attention_mask"] + [0]      * n_pad)
            labels.append  (x["labels"]         + [-100]   * n_pad)
        return {
            "input_ids"     : torch.tensor(input_ids),
            "attention_mask": torch.tensor(attn),
            "labels"        : torch.tensor(labels),
        }

    return collate


def extract_curves(log_history: list) -> dict:
    """
    Parse Trainer log_history into clean train/eval loss curves.
    Returns dict with epoch lists, train losses, eval losses.
    """
    train_curve = []
    eval_curve  = []
    for entry in log_history:
        if "loss" in entry and "epoch" in entry and "eval_loss" not in entry:
            train_curve.append({
                "epoch": round(entry["epoch"], 3),
                "step" : entry.get("step"),
                "loss" : round(entry["loss"], 4),
            })
        if "eval_loss" in entry:
            eval_curve.append({
                "epoch"    : round(entry["epoch"], 3),
                "step"     : entry.get("step"),
                "eval_loss": round(entry["eval_loss"], 4),
            })
    return {"train": train_curve, "eval": eval_curve}


def train_one_size(size_k: int, tokenizer) -> dict:
    """Fine-tune a fresh student on tweets_clean_{size_k}k.jsonl."""
    section(f"Training student on {size_k}k tweets")

    dataset_path = os.path.join(CLEAN_DATASETS_DIR, f"tweets_clean_{size_k}k.jsonl")
    if not os.path.exists(dataset_path):
        print(f"  ⚠  Dataset not found: {dataset_path} — skipping.")
        return {"status": "skipped", "reason": "missing dataset"}

    output_dir   = os.path.join(ADAPTERS_DIR, f"student_{size_k}k")
    checkpoint_dir = os.path.join(WORK_DIR, "_tmp_checkpoints", f"student_{size_k}k")
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(checkpoint_dir, exist_ok=True)

    # ── Load + split + tokenise ───────────────────────────────
    train_ds, eval_ds = build_train_eval_splits(dataset_path, tokenizer)

    if size_k == DATASET_SIZES[0]:
        sample = train_ds[0]
        n_unmasked = sum(1 for x in sample["labels"] if x != -100)
        print(f"  Sample tokens: total={len(sample['labels'])}  "
              f"trainable={n_unmasked}  masked={len(sample['labels']) - n_unmasked}")

    # ── Load fresh model + adapter ────────────────────────────
    print("  Loading base model + LoRA adapter…")
    model = load_base_model()
    trainable, total = model.get_nb_trainable_parameters()
    print(f"  Trainable params : {trainable:,} / {total:,}  "
          f"({100*trainable/total:.2f}%)")

    # ── Training arguments ────────────────────────────────────
    args = TrainingArguments(
        output_dir                   = checkpoint_dir,
        num_train_epochs             = NUM_EPOCHS,
        per_device_train_batch_size  = BATCH_SIZE,
        per_device_eval_batch_size   = BATCH_SIZE,
        gradient_accumulation_steps  = GRAD_ACCUM_STEPS,
        learning_rate                = LEARNING_RATE,
        warmup_ratio                 = WARMUP_RATIO,
        weight_decay                 = WEIGHT_DECAY,
        logging_steps                = LOGGING_STEPS,

        # Evaluation + early stopping
        eval_strategy                = "epoch",
        save_strategy                = "epoch",
        save_total_limit             = 2,        # keep at most 2 checkpoints on disk
        load_best_model_at_end       = True,
        metric_for_best_model        = "eval_loss",
        greater_is_better            = False,

        bf16                         = True,
        optim                        = "paged_adamw_8bit",
        report_to                    = "none",
        seed                         = SEED,
        remove_unused_columns        = False,
    )

    trainer = Trainer(
        model         = model,
        args          = args,
        train_dataset = train_ds,
        eval_dataset  = eval_ds,
        data_collator = make_collator(tokenizer),
        callbacks     = [EarlyStoppingCallback(
            early_stopping_patience  = EARLY_STOPPING_PATIENCE,
            early_stopping_threshold = EARLY_STOPPING_THRESHOLD,
        )],
    )

    # ── Train ─────────────────────────────────────────────────
    t0 = time.time()
    train_result = trainer.train()
    train_time   = time.time() - t0

    # Final eval (best model has been re-loaded automatically)
    final_eval = trainer.evaluate()
    final_eval_loss = final_eval.get("eval_loss")

    # ── Save the BEST adapter ─────────────────────────────────
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"  ✓ Best adapter saved → {output_dir}")
    print(f"  Training time      : {train_time/60:.1f} min")
    print(f"  Final train loss   : {train_result.training_loss:.4f}")
    print(f"  Best eval loss     : {final_eval_loss:.4f}")

    # ── Cleanup checkpoints to save disk ──────────────────────
    try:
        import shutil
        shutil.rmtree(checkpoint_dir, ignore_errors=True)
    except Exception:
        pass

    # ── Extract curves ────────────────────────────────────────
    curves = extract_curves(trainer.state.log_history)

    # Detect early stop
    n_epochs_used = curves["eval"][-1]["epoch"] if curves["eval"] else NUM_EPOCHS
    early_stopped = n_epochs_used < NUM_EPOCHS

    # Free GPU
    del trainer, model
    torch.cuda.empty_cache()

    return {
        "status"            : "trained",
        "size_k"            : size_k,
        "n_train"           : len(train_ds),
        "n_eval"            : len(eval_ds),
        "max_epochs"        : NUM_EPOCHS,
        "epochs_completed"  : round(n_epochs_used, 2),
        "early_stopped"     : early_stopped,
        "final_train_loss"  : round(train_result.training_loss, 4),
        "best_eval_loss"    : round(final_eval_loss, 4),
        "train_time_min"    : round(train_time / 60, 1),
        "adapter_path"      : output_dir,
        "curves"            : curves,
    }


# ──────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────
def main():
    sizes = DATASET_SIZES
    if len(sys.argv) > 1:
        sizes = [int(a) for a in sys.argv[1:]]
        print(f"  CLI override: training only sizes {sizes}")

    print("\n" + "=" * 62)
    print("  SUBLIMINAL LEARNING — PHASE B: STUDENT FINE-TUNING")
    print("=" * 62)
    print(f"  Reference model      : {MODEL_ID}")
    print(f"  LoRA r / alpha       : {LORA_R} / {LORA_ALPHA}")
    print(f"  Max epochs           : {NUM_EPOCHS}")
    print(f"  Batch size           : {BATCH_SIZE} × {GRAD_ACCUM_STEPS} = "
          f"{BATCH_SIZE * GRAD_ACCUM_STEPS} effective")
    print(f"  Learning rate        : {LEARNING_RATE}")
    print(f"  Eval fraction        : {EVAL_FRACTION:.0%}")
    print(f"  Early stop patience  : {EARLY_STOPPING_PATIENCE} epochs")
    print(f"  Sizes to train       : {sizes}  (×1000)")

    os.makedirs(ADAPTERS_DIR, exist_ok=True)

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    all_results = {}
    overall_t0 = time.time()

    for size_k in sizes:
        try:
            result = train_one_size(size_k, tokenizer)
            all_results[f"{size_k}k"] = result
        except Exception as e:
            print(f"\n  ✗ Failed on {size_k}k: {e}")
            all_results[f"{size_k}k"] = {"status": "failed", "error": str(e)}
            torch.cuda.empty_cache()

    overall_time = time.time() - overall_t0

    # ── Summary ───────────────────────────────────────────────
    section("Training Summary")
    header = f"  {'Size':<6} {'Status':<10} {'Train':>7} {'Eval':>7} {'Epochs':>10} {'Stopped':>9} {'Time(min)':>11}"
    print(header)
    print(f"  {'─'*6} {'─'*10} {'─'*7} {'─'*7} {'─'*10} {'─'*9} {'─'*11}")
    for key, r in all_results.items():
        if r["status"] == "trained":
            print(f"  {key:<6} {r['status']:<10} "
                  f"{r['final_train_loss']:>7.4f} "
                  f"{r['best_eval_loss']:>7.4f} "
                  f"{r['epochs_completed']:>10.2f} "
                  f"{'yes' if r['early_stopped'] else 'no':>9} "
                  f"{r['train_time_min']:>11.1f}")
        else:
            print(f"  {key:<6} {r['status']:<10} {'-':>7} {'-':>7} {'-':>10} {'-':>9} {'-':>11}")

    print(f"\n  Total wall-clock time : {overall_time/60:.1f} min")

    # ── Save report ───────────────────────────────────────────
    report = {
        "experiment"     : "04_finetune_student",
        "model_id"       : MODEL_ID,
        "training_config": {
            "max_epochs"         : NUM_EPOCHS,
            "batch_size"         : BATCH_SIZE,
            "grad_accum_steps"   : GRAD_ACCUM_STEPS,
            "effective_batch"    : BATCH_SIZE * GRAD_ACCUM_STEPS,
            "learning_rate"      : LEARNING_RATE,
            "warmup_ratio"       : WARMUP_RATIO,
            "max_seq_len"        : MAX_SEQ_LEN,
            "eval_fraction"      : EVAL_FRACTION,
            "split_seed"         : SPLIT_SEED,
            "early_stop_patience": EARLY_STOPPING_PATIENCE,
            "lora_r"             : LORA_R,
            "lora_alpha"         : LORA_ALPHA,
            "lora_dropout"       : LORA_DROPOUT,
            "lora_target_modules": LORA_TARGETS,
            "seed"               : SEED,
        },
        "runs"           : all_results,
        "total_time_min" : round(overall_time / 60, 1),
    }
    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print(f"\n  Report   → {REPORT_FILE}")
    print(f"  Adapters → {ADAPTERS_DIR}/")
    print("\n" + "=" * 62 + "\n")


if __name__ == "__main__":
    main()
